### ISSUE TITLE
Document all environment variables used

### ISSUE THREAD

**Issue by Cobular** [codeday/johnpeter-discord#10]
While fixing issue #9 , I realized that I don't think there is a good place where all the environment variables that are used are documented. Most of them are in Vault, but there are some testing related ones that as far as I'm aware only exist in @oohwooh and I's pycharm run configurations. I think it should be safe to put all the env var names here, although I won't start documenting them until I get the OK from someone else in case there's some potential issue I don't see.

**Comment by oohwooh** [comment]
I can't think of any potential issues from documentation, nothing anybody couldn't learn from just analyzing the code. There are probably a bunch of outdated things that are now useless from the run configurations though

**Comment by chennnyl** [comment]
This issue can probably be closed since #27 lol
