### ISSUE TITLE
Reaction roles feature doesn't save state 

### ISSUE THREAD

**Issue by oohwooh** [codeday/johnpeter-discord#11]
I forgot this was the case, making this issue so I don't forget to fix it. Also will add retroactive support

**Comment by oohwooh** [comment]
So I'm just going to hotfix this and make it use pickle since that will be faster to implement, @JakeCover when you have the time could you integrate this with the database? It's the reactions cog

**Comment by oohwooh** [comment]
Oh wait that wont be the right kind of persistent, I'll make it use the database

**Comment by Cobular** [comment]
@oohwooh do you have the database stuff covered already? I can totally do it if you still need me to.
