### ISSUE TITLE
Sort badge display alphabetically (or consistently)

### ISSUE THREAD

**Issue by itsmingjie** [codeday/johnpeter-discord#13]
Would think it'd be less messy if they are always ordered alphabetically or in a consistent order. 

E.g.:
* "Verified" always ranked first

other ideas tbd

**Comment by oohwooh** [comment]
Are you thinking the display of them when listed, or when actually in the name, or both?

**Comment by itsmingjie** [comment]
Actually in the name (more important), or both! Looks nicer that way imo
