### ISSUE TITLE
Announcements: Escape/Convert HTML

### ISSUE THREAD

**Issue by itsmingjie** [codeday/johnpeter-discord#16]
John Peter is now posting announcements in HTML (see [sample](https://discord.com/channels/689213562740277361/689213563247656997/786649757618536459)). It'd better if the content can be stripped or converted to Discord-supported Markdown (only bold, italics, strikethrough, and underline are supported? so links have to be a different case from regular MD conversion)

https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-

**Comment by Nexite** [comment]
Convert the entire thing to an embed which would let you do links and markdown 
https://stackoverflow.com/questions/64527464/clickable-link-inside-message-discord-py

**Comment by itsmingjie** [comment]
Oh awesome! Yeah that looks ideal too

**Comment by itsmingjie** [comment]
Discord Embed also has 48 chars higher character limit LOL

**Comment by oohwooh** [comment]
This has been finally fixed in #36
