### ISSUE TITLE
outdated help text referencing staff user color

### ISSUE THREAD

**Issue by itsmingjie** [codeday/johnpeter-discord#18]
We should either mark empoyeels/staff as a different color, or just tell people to find people with the role (harder to find). Bots are also red now LOL

https://github.com/codeday/johnpeter-discord/blob/master/src/cogs/cleverbot.py#L48

**Comment by chennnyl** [comment]
Fixed this in #22

**Comment by itsmingjie** [comment]
Awesome, closing
