### ISSUE TITLE
Nitpick: checking for staff roles is very repetitive

### ISSUE THREAD

**Issue by oohwooh** [codeday/johnpeter-discord#9]
Right now staff-only commands are using the `has_any_role` decorator with "Employee" and "Staff" manually specified. This makes changing them a pain, as was the case from the "Global Staff" -> "Employee" change a couple months ago. (See  [4fa0172](https://github.com/codeday/johnpeter-discord/commit/4fa0172477935fefbe556682dd9585d2b25aeb81))

I propose 2 possible solutions:
* creating a `requires_staff_role` decorator that wraps `has_any_role` but with specified staff roles, so if these must be changed it goes there
or
* checking permissions of the user instead of specific roles, maybe seeing if they have read access to the #staff channel as a way to test for admin?

I think the former solution is easiest to implement and ties in with our existing permission scheme.

**Comment by chennnyl** [comment]
This has also since been resolved
